apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: podmonitors.monitoring.coreos.com
spec:
  group: monitoring.coreos.com
  names:
    kind: PodMonitor
    plural: podmonitors
  scope: Namespaced
  validation:
    openAPIV3Schema:
      type: object
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values.'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents.'
          type: string
        spec:
          description: PodMonitorSpec contains specification parameters for a PodMonitor.
          type: object
          properties:
            jobLabel:
              description: The label to use to retrieve the job name from.
              type: string
            namespaceSelector:
              description: NamespaceSelector is a selector for selecting either all
                namespaces or a list of namespaces.
              type: object
              properties:
                any:
                  type: boolean
                matchNames:
                  type: array
                  items:
                    type: string
            podMetricsEndpoints:
              description: A list of endpoints allowed as part of this PodMonitor.
              type: array
              items:
                type: object
                properties:
                  honorLabels:
                    type: boolean
                  interval:
                    type: string
                  metricRelabelings:
                    type: array
                    items:
                      type: object
                      properties:
                        action:
                          type: string
                        regex:
                          type: string
                        replacement:
                          type: string
                        sourceLabels:
                          type: array
                          items:
                            type: string
                        targetLabel:
                          type: string
                  path:
                    type: string
                  port:
                    type: string
                  relabelings:
                    type: array
                    items:
                      type: object
                      properties:
                        action:
                          type: string
                        regex:
                          type: string
                        replacement:
                          type: string
                        sourceLabels:
                          type: array
                          items:
                            type: string
                        targetLabel:
                          type: string
                  scheme:
                    type: string
                  scrapeTimeout:
                    type: string
            podTargetLabels:
              type: array
              items:
                type: string
            sampleLimit:
              type: integer
            selector:
              description: A label selector is a label query over a set of resources.
              type: object
              properties:
                matchLabels:
                  type: object
                matchExpressions:
                  type: array
                  items:
                    type: object
                    properties:
                      key:
                        type: string
                      operator:
                        type: string
                      values:
                        type: array
                        items:
                          type: string
          required:
            - podMetricsEndpoints
            - selector
      required:
        - apiVersion
        - kind
        - spec
  versions:
  - name: v1
    served: true
    storage: true
