apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30031
  selector:
    app: grafana

    type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30030