apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  namespace: monitoring
  labels:
    k8s-app: cadvisor
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30031
  selector:
    k8s-app: cadvisor

