kind: Service
apiVersion: v1
metadata:
  name: cadvisor
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30001
      targetPort: 8080
      protocol: TCP
  selector:
    app: cadvisor
