apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  namespace: monitoring
spec:
  type: NodePort # Cambiar a LoadBalancer si es necesario
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001 # Cambiar según tu entorno
  selector:
    app: cadvisor
