apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  namespace: monitoring
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    k8s-app: cadvisor

#apiVersion: v1
#kind: Service
#metadata:
  #name: cadvisor
  #namespace: monitoring
#spec:
  #type: NodePort
  #ports:
   # - port: 8080
    #  targetPort: 8080
     # nodePort: 30001
  #selector:
   # k8s-app: cadvisor