apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  namespace: monitoring
  labels:
    k8s-app: cadvisor
spec:
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
  selector:
    k8s-app: cadvisor
  type: ClusterIP
