apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: node-exporter
  name: node-exporter
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - name: metrics
    port: 9100
    targetPort: 9100
    nodePort: 30100
  selector:
    k8s-app: node-exporter