apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: node-exporter
  name: node-exporter
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - name: metrics
      port: 9100       # Puerto en el contenedor
      targetPort: 9100 # Puerto en el pod donde corre node-exporter
      nodePort: 30002  # Puerto que usará el nodo para exponer el servicio
  selector:
    k8s-app: node-exporter
