apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 48.3.1
    chart: kube-prometheus-stack
    helm:
      values: |
        grafana:
          enabled: true
          adminPassword: "admin123"  # Cambia esto en producción
          
          dashboardProviders:
            dashboardproviders.yaml:
              apiVersion: 1
              providers:
                - name: 'default'
                  orgId: 1
                  folder: ''
                  type: file
                  disableDeletion: false
                  editable: true
                  options:
                    path: /var/lib/grafana/dashboards/default

          dashboards:
            default:
              # Dashboard para Kubernetes Pods
              k8s-pods:
                gnetId: 12740
                revision: 1
                datasource: Prometheus
              # Dashboard para Nodes
              k8s-nodes:
                gnetId: 315
                revision: 3
                datasource: Prometheus
              # Dashboard para métricas del Cluster
              k8s-cluster:
                gnetId: 7249
                revision: 1
                datasource: Prometheus
              # Dashboard para métricas por Namespace
              k8s-namespaces:
                gnetId: 15758
                revision: 1
                datasource: Prometheus
              # Dashboard para uso de recursos
              k8s-resources:
                gnetId: 13105
                revision: 1
                datasource: Prometheus

          additionalDataSources:
            - name: Prometheus
              type: prometheus
              url: http://prometheus-operated:9090
              access: proxy
              isDefault: true
              
          grafana.ini:
            auth.anonymous:
              enabled: true
              org_role: Viewer

        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
            retention: 30d
            resources:
              requests:
                cpu: 200m
                memory: 2Gi
            storageSpec:
              volumeClaimTemplate:
                spec:
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 50Gi

            additionalScrapeConfigs:
              - job_name: 'kubernetes-pods'
                kubernetes_sd_configs:
                  - role: pod
                relabel_configs:
                  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
                    action: keep
                    regex: true
                  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
                    action: replace
                    target_label: __metrics_path__
                    regex: (.+)
                  - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
                    action: replace
                    regex: (.+):(?:\d+);(\d+)
                    replacement: ${1}:${2}
                    target_label: __address__
                  - action: labelmap
                    regex: __meta_kubernetes_pod_label_(.+)
                  - source_labels: [__meta_kubernetes_namespace]
                    action: replace
                    target_label: kubernetes_namespace
                  - source_labels: [__meta_kubernetes_pod_name]
                    action: replace
                    target_label: kubernetes_pod_name

        kubeStateMetrics:
          enabled: true

        nodeExporter:
          enabled: true
          
        alertmanager:
          enabled: true
          
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true