apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: monitoring
data:
  promtail.yaml: |
    scrape_configs:
      - job_name: "laravel-logs"
        static_configs:
          - targets:
              - localhost
            labels:
              job: "laravel"
              instance: "minikube"
              __path__: "/var/log/laravel/*.log"
