apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-simulado
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""  
  hostPath:
    path: "/mnt/efs-simulado"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc
spec:
  storageClassName: ""  
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi


