apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tu-repo/k8s-monitoring.git
    path: monitoring/grafana
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.56.0
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://EKS-MONITORING-CLUSTER
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
