adminUser: admin
adminPassword: admin123

service:
  type: NodePort
  ports:
    - name: http
      port: 3008
      targetPort: 3008
      nodePort: 30001
  selector:
    app: grafana

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.monitoring.svc.cluster.local:80
        access: proxy
        isDefault: true
      - name: Loki
        type: loki
        url: http://loki.monitoring.svc.cluster.local:3100
        access: proxy

dashboardProviders:
  dashboardProviders.yaml:
    apiVersion: 1
    providers:
      - name: default
        orgId: 1
        folder: ""
        type: file
        disableDeletion: true
        updateIntervalSeconds: 10
        options:
          path: /var/lib/grafana/dashboards

dashboards:
  default:
    kubernetes:
      gnetId: 315
      revision: 1
      datasource: Prometheus
    redis:
      gnetId: 11830
      revision: 1
      datasource: Prometheus
    rds-queries:
      gnetId: 13623
      revision: 1
      datasource: Prometheus
    namespace-monitoring:
      json: |
        {
          "dashboard": {
            "title": "Estado y Consumo por Namespace",
            "panels": [
              {
                "title": "Pods en Buen Estado",
                "type": "stat",
                "targets": [
                  {
                    "expr": "count(kube_pod_status_phase{phase='Running'}) by (namespace)"
                  }
                ]
              },
              {
                "title": "Pods en Mal Estado",
                "type": "stat",
                "targets": [
                  {
                    "expr": "count(kube_pod_status_phase{phase=~'Failed|CrashLoopBackOff'}) by (namespace)"
                  }
                ]
              },
              {
                "title": "Pods en Construcción",
                "type": "stat",
                "targets": [
                  {
                    "expr": "count(kube_pod_status_phase{phase=~'Pending|ContainerCreating'}) by (namespace)"
                  }
                ]
              },
              {
                "title": "Consumo de CPU por Pod",
                "type": "graph",
                "targets": [
                  {
                    "expr": "sum(rate(container_cpu_usage_seconds_total[5m])) by (pod)"
                  }
                ]
              },
              {
                "title": "Uso de Memoria por Pod",
                "type": "graph",
                "targets": [
                  {
                    "expr": "sum(container_memory_usage_bytes) by (pod)"
                  }
                ]
              }
            ]
          }
        }


