apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: argocd
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-repo-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-repo-server
    spec:
      volumes:
        - name: argocd-repo-data
          persistentVolumeClaim:
            claimName: argocd-pvc
        - name: custom-tools
          emptyDir: {}
        - name: argocd-repo-server-tls
          emptyDir: {}
      containers:
        - name: argocd-repo-server
          image: quay.io/argoproj/argocd:v2.12.3  # Añadida la imagen específica
          volumeMounts:
            - name: argocd-repo-data
              mountPath: /app/config
              subPath: repo-server
            - name: argocd-repo-data
              mountPath: /app/ssh
              subPath: ssh



