apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30007
    - name: https
      port: 443
      targetPort: 8080
      nodePort: 30008
  selector:
    app.kubernetes.io/name: argocd-server