apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-application-controller
  namespace: argocd
spec:
  selector:
    matchLabels:
      app: argocd-application-controller
  template:
    metadata:
      labels:
        app: argocd-application-controller
    spec:
      volumes:
        - name: argocd-repo-data
          persistentVolumeClaim:
            claimName: argocd-pvc
      containers:
        - name: argocd-application-controller
          image: quay.io/argoproj/argocd:v2.12.3  # Añadida la imagen específica
          volumeMounts:
            - name: argocd-repo-data
              mountPath: /app/config
              subPath: controller
