apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: monitoring
  labels:
    grafana_dashboard: "1"
data:
  kubernetes-cluster-dashboard.json: |
    {
      "dashboard": {
        "id": null,
        "uid": "k8s-cluster",
        "title": "Kubernetes Cluster Monitoring",
        "tags": ["kubernetes"],
        "timezone": "browser",
        "schemaVersion": 16,
        "version": 0,
        "refresh": "5s",
        "panels": [
          {
            "type": "graph",
            "title": "CPU Usage",
            "targets": [
              {
                "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[5m])) by (pod)",
                "legendFormat": "{{pod}}",
                "refId": "A"
              }
            ]
          },
          {
            "type": "graph",
            "title": "Memory Usage",
            "targets": [
              {
                "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\"}) by (pod)",
                "legendFormat": "{{pod}}",
                "refId": "B"
              }
            ]
          }
        ],
        "templating": {
          "list": [
            {
              "type": "query",
              "name": "namespace",
              "label": "Namespace",
              "datasource": "Prometheus",
              "query": "label_values(kube_pod_info, namespace)",
              "refresh": 1
            }
          ]
        }
      }
    }
