apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grafana
rules:
  - apiGroups: [""]
    resources:
      - configmaps
      - secrets
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources:
      - pods
    verbs: ["list", "create", "delete"]
  - apiGroups: [""]
    resources:
      - services
    verbs: ["get", "list", "watch"]
