apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rmhiguerey/manifiestos.git
    path: stackmonitoring/
    targetRevision: main
    helm:
      releaseName: grafana
      chart: grafana
      repo: https://grafana.github.io/helm-charts
      version: 6.56.0
      valueFiles:
        - values-grafana.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true







