apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-helm-values
  namespace: monitoring
data:
  values.yaml: |
    adminUser: admin
    adminPassword: admin123
    
    service:
      type: NodePort
      ports:
        - name: http
          port: 3000
          targetPort: 3000
          nodePort: 30001
    
    persistence:
      enabled: true
      size: 10Gi
    
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            url: http://prometheus.monitoring.svc.cluster.local:9090
            access: proxy
            isDefault: true
          - name: Loki
            type: loki
            url: http://loki.monitoring.svc.cluster.local:3100
            access: proxy
    
    dashboardProviders:
      dashboardProviders.yaml:
        apiVersion: 1
        providers:
          - name: default
            orgId: 1
            folder: ''
            type: file
            disableDeletion: true
            updateIntervalSeconds: 10
            options:
              path: /var/lib/grafana/dashboards
    
    dashboards:
      default:
        kubernetes:
          gnetId: 315
          revision: 1
          datasource: Prometheus
        redis:
          gnetId: 11830
          revision: 1
          datasource: Prometheus
        rds-queries:
          gnetId: 13623
          revision: 1
          datasource: Prometheus   
    
    grafana:
      externalUrl: http://MINIKUBE-IP:30001



