apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: grafana
      targetRevision: 6.56.0
      helm:
        valueFiles:
          - $values/stackmonitoring/values-grafana.yaml
    - repoURL: https://github.com/rmhiguerey/manifiestos.git
      targetRevision: main
      path: stackmonitoring
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true








