apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: grafana
      targetRevision: 6.56.0
      helm:
        valueFiles:
          - stackmonitoring/grafana/values-grafana.yaml
    - repoURL: https://github.com/rmhiguerey/manifiestos.git
      path: stackmonitoring/grafana
      targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true





