apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  sources:
    - chart: prometheus
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 25.0.0
      helm:
        valuesFiles:
          - $values/stackmonitoring/prometheus-values.yaml
    - repoURL: https://github.com/rmhiguerey/manifiestos.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

